<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-3867</name>
   <tag></tag>
   <elementGuidId>f46fb71d-b46e-4640-8eb9-96af33865d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-3867</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2224455-3d5c-4332-a0d2-a719b5b931c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-3867</value>
      <webElementGuid>6c723645-05da-4bf0-a789-7ff5761d2451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9669d5c-c22e-4408-b1cd-181247fab4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-3867&quot;)</value>
      <webElementGuid>93d42ad9-147b-4e25-87ad-c2e1d2e2a4d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-3867']</value>
      <webElementGuid>6758db19-0eb0-4b3e-9e64-2a8e5753179c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>6e078fce-13d2-4e25-bf4c-a35bed60fbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>9deed37c-217b-4a6a-b45d-7194f69ab5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-3867' and @type = 'text']</value>
      <webElementGuid>121f4e84-594c-47ce-9045-5ea70eb40b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
