<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DetailBeli</name>
   <tag></tag>
   <elementGuidId>8b6d0a06-a4e7-49fe-a661-6c17a9852ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#85139 > div.v-card.v-sheet.theme--light > div.v-card__actions.d-block > div.mt-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='85139']/div/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41e63953-9a65-4d72-a151-722a8b306dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3</value>
      <webElementGuid>38e830a7-67af-4059-a868-8e4553397a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DetailBeli</value>
      <webElementGuid>87d6f961-9100-45e2-81ee-03bb7a612533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;85139&quot;)/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__actions d-block&quot;]/div[@class=&quot;mt-3&quot;]</value>
      <webElementGuid>ca1b88f1-d9b8-487e-8a7a-1010994d1a3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='85139']/div/div[3]/div[2]</value>
      <webElementGuid>70dc9283-19cf-46f7-a2db-8ef433ed374c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]/div[2]</value>
      <webElementGuid>4832cc65-ab40-400e-a6c0-ae518f5bf173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DetailBeli' or . = 'DetailBeli')]</value>
      <webElementGuid>058d4861-711e-4f6a-b827-53e9e6ceca1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
