<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sony PS5Rp 299 (0)</name>
   <tag></tag>
   <elementGuidId>3b55c834-03c6-4c00-b222-62f774a2a5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e4c84c1-b0de-49b8-a6b0-66f649e6f814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>8d472c2b-6ce0-4020-94e4-f682b8be65de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sony PS5Rp 299 (0) </value>
      <webElementGuid>4d21214f-0a0d-4b8e-b8d6-f46b31dff34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]</value>
      <webElementGuid>b43adf7a-3582-425c-85c1-8507f612179d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div</value>
      <webElementGuid>f6f03f2f-f7bb-4b2c-b08f-6d3c6658eb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[4]</value>
      <webElementGuid>49d6e59c-5c0b-4cc9-9590-16e5888075ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div</value>
      <webElementGuid>9dc3143f-bd26-47fb-a665-5ea53b83d429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sony PS5Rp 299 (0) ' or . = 'Sony PS5Rp 299 (0) ')]</value>
      <webElementGuid>a4e00ef8-4dac-4b65-95c2-304046e4f21e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
